# Generated by Django 4.1.7 on 2023-04-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('describe', models.TextField(verbose_name='Описание')),
                ('image', models.TextField(verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'AMG',
                'verbose_name_plural': 'AMGs',
            },
        ),
        migrations.CreateModel(
            name='Cabriolet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('describe', models.TextField(verbose_name='Описание')),
                ('image', models.TextField(verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Cabriolet',
                'verbose_name_plural': 'Cabriolets',
            },
        ),
        migrations.CreateModel(
            name='Electric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('describe', models.TextField(verbose_name='Описание')),
                ('image', models.TextField(verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Electric',
                'verbose_name_plural': 'Electric',
            },
        ),
        migrations.CreateModel(
            name='Eq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('describe', models.TextField(verbose_name='Описание')),
                ('image', models.TextField(verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Eq',
                'verbose_name_plural': 'Eqs',
            },
        ),
        migrations.CreateModel(
            name='Gazoline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('describe', models.TextField(verbose_name='Описание')),
                ('image', models.TextField(verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Gazoline',
                'verbose_name_plural': 'Gazoline',
            },
        ),
        migrations.CreateModel(
            name='Minivan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('describe', models.TextField(verbose_name='Описание')),
                ('image', models.TextField(verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Minivan',
                'verbose_name_plural': 'Minivans',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('describe', models.TextField(verbose_name='Описание')),
                ('image', models.TextField(verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'New',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('image', models.TextField(verbose_name='Картинка')),
                ('topic', models.TextField(verbose_name='Заголовок')),
                ('describe', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Sedan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('describe', models.TextField(verbose_name='Описание')),
                ('image', models.TextField(verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Sedan',
                'verbose_name_plural': 'Sedans',
            },
        ),
    ]
